spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2ddd;AUTO_SERVER=true
    username: sa
    password:
  h2:
    console:
      enabled: true
server:
  port: 8099
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE